export const ACTIONS = {
    AUTH: "AUTH",
    AUTH_READY: "AUTH_READY",
    AUTH_TYPE: "AUTH_TYPE",
    USER: "USER",
    GET_CATEGORIES: "GET_CATEGORIES",
    POSTS: "POSTS",
    ADD_POST: "ADD_POST",
    EDIT_POST: "EDIT_POST",
    DELETE_POST: "DELETE_POST",
    UPDATE_NAME: "UPDATE_NAME",
    UPDATE_IMAGE: "UPDATE_IMAGE"
}