
export const ACTIONS = {
    AUTH: "AUTH",
    AUTH_READY: "AUTH_READY",
    AUTH_TYPE: "AUTH_TYPE",
    GET_PRODUCTS: "GET_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    ADD_CART:"ADD_CART",
    DELETE_CART:"DELETE_CART",
    INCREASE_NUMBER_PRODUCT:"INCREASE_NUMBER_PRODUCT",
    DECREASE_NUMBER_PRODUCT:"DECREASE_NUMBER_PRODUCT",
    ADD_ALL_CART: "ADD_ALL_CART",
}

