import Head from "next/head"
import SwiperCore, { Autoplay, Navigation } from "swiper/core"
import React, { useContext } from "react"
import Hero from "../sections/Home/Hero"
// import OurCategories from "../sections/Home/OurCategories"
// import Reason from "../sections/Home/Reason"
// import JoinUs from "../sections/Home/JoinUs"
// import FeaturedServices from "../sections/Home/FeaturedServices"
import Layout from "../components/Layout"
import Products from "../sections/Home/Products"
import Requests from "../sections/Home/Requests"
import MangnamentProduct from "../sections/Home/MangnamentProduct"
import { DataContext } from "../store/GlobalState"

SwiperCore.use([Autoplay, Navigation])

export default function Home({products}) {
  const { state } = useContext(DataContext)
  const { auth, authReady } = state
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav >
        {
          authReady ? (
            <>
              {
                auth.user?.role === "admin" ?
                (
                  <>
                    {/* <Requests/> */}
                    <Hero/>
                    <MangnamentProduct  products={products}/>
                  </>
                )
                :(
                  <>
                    <Hero/>
                    <Products products={products}/>
                  </>
                )
              }
            </>
          ):null
        }
      </Layout>
    </div>
  )
}

export const getServerSideProps = async context => {
  // const id = context.params.id
  const res = await fetch(`${process.env.API_BASE_URL}/post/all`)
  // @ts-ignore
  const data = await res.json()
  return {
    props: { products: data.posts }
  }
}