import Head from "next/head"
import SwiperCore, { Autoplay, Navigation } from "swiper/core"
import React from "react"
import Hero from "../sections/Home/Hero"
// import OurCategories from "../sections/Home/OurCategories"
// import Reason from "../sections/Home/Reason"
// import JoinUs from "../sections/Home/JoinUs"
// import FeaturedServices from "../sections/Home/FeaturedServices"
import Layout from "../components/Layout"
import Products from "../sections/Home/Products"
import Requests from "../sections/Home/Requests"
import MangnamentProduct from "../sections/Home/MangnamentProduct"

SwiperCore.use([Autoplay, Navigation])

export default function Home() {
  const role = "user"
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav >
        {
          role === "admin" ?
          (
            <>
              <Requests/>
              <MangnamentProduct/>
            </>
          )
          :(
            <>
              <Hero/>
              <Products/>
            </>
          )
        }
       
      </Layout>
    </div>
  )
}