import Head from "next/head"
import Layout from "../components/Layout"

export default function MisCompras() {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav withFooter>
          <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi tempora cum labore voluptas recusandae molestiae vel, suscipit ratione provident sed vitae officiis voluptatibus sint, architecto quos dicta. Dolorem numquam sit dicta ipsa totam assumenda maxime et nisi nulla. Rem consequatur dicta, corporis ad ipsum repudiandae doloremque non iusto reiciendis facilis, quam voluptas? Cumque rem quam doloribus iusto nulla quia neque voluptatem aliquam vel et consectetur non laboriosam, tenetur tempore facilis.</div>
          <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi tempora cum labore voluptas recusandae molestiae vel, suscipit ratione provident sed vitae officiis voluptatibus sint, architecto quos dicta. Dolorem numquam sit dicta ipsa totam assumenda maxime et nisi nulla. Rem consequatur dicta, corporis ad ipsum repudiandae doloremque non iusto reiciendis facilis, quam voluptas? Cumque rem quam doloribus iusto nulla quia neque voluptatem aliquam vel et consectetur non laboriosam, tenetur tempore facilis.</div>
          <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi tempora cum labore voluptas recusandae molestiae vel, suscipit ratione provident sed vitae officiis voluptatibus sint, architecto quos dicta. Dolorem numquam sit dicta ipsa totam assumenda maxime et nisi nulla. Rem consequatur dicta, corporis ad ipsum repudiandae doloremque non iusto reiciendis facilis, quam voluptas? Cumque rem quam doloribus iusto nulla quia neque voluptatem aliquam vel et consectetur non laboriosam, tenetur tempore facilis.</div>
          <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi tempora cum labore voluptas recusandae molestiae vel, suscipit ratione provident sed vitae officiis voluptatibus sint, architecto quos dicta. Dolorem numquam sit dicta ipsa totam assumenda maxime et nisi nulla. Rem consequatur dicta, corporis ad ipsum repudiandae doloremque non iusto reiciendis facilis, quam voluptas? Cumque rem quam doloribus iusto nulla quia neque voluptatem aliquam vel et consectetur non laboriosam, tenetur tempore facilis.</div>
      </Layout>
    </div>
    )
}
