import Head from "next/head"
import Layout from "../components/Layout"
import {
  Grid,
  Box,
  Text
} from "@chakra-ui/react"
import CardBuyed from "../components/CardBuyed"

export default function MisCompras() {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav >
          <Box bg="primary">
            <Box className="generalWrapper">
              <Text color="letter" fontSize="2xl" fontWeight="medium" textAlign="center" py="12">Mis compras</Text>
              <Grid templateColumns="repeat(4,1fr)">
                  {
                    [1,2,3,4,5].map(item=>(
                      <CardBuyed key={item}/>
                    ))
                  }
              </Grid>
            </Box>
          </Box>
      </Layout>
    </div>
    )
}

// export const getServerSideProps = async context => {
//   // const id = context.params.id
//   const res = await fetch(`${process.env.API_BASE_URL}/buy/:usuario`)
//   // @ts-ignore
//   const data = await res.json()
//   return {
//     props: { products: data.posts }
//   }
// }


